################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
opencv/samples/wp8/OpenCVXaml/OpenCVComponent \
opencv/samples/wp8/OcvRotatingCube/PhoneXamlDirect3DApp1/PhoneXamlDirect3DApp1Comp \
opencv/samples/wp8/OcvImageManipulation/PhoneXamlDirect3DApp1/PhoneXamlDirect3DApp1Comp \
opencv/samples/winrt_universal/VideoCaptureXAML/video_capture_xaml/video_capture_xaml.WindowsPhone \
opencv/samples/winrt_universal/VideoCaptureXAML/video_capture_xaml/video_capture_xaml.Windows \
opencv/samples/winrt_universal/VideoCaptureXAML/video_capture_xaml/video_capture_xaml.Shared \
opencv/samples/winrt_universal/PhoneTutorial \
opencv/samples/winrt/OcvImageProcessing/OcvImageProcessing \
opencv/samples/winrt/ImageManipulations \
opencv/samples/winrt/ImageManipulations/common \
opencv/samples/winrt/ImageManipulations/MediaExtensions/OcvTransform \
opencv/samples/winrt/FaceDetection/FaceDetection \
opencv/samples/va_intel \
opencv/samples/tapi \
opencv/samples/opengl \
opencv/samples/opencl \
opencv/samples/hal/slow_hal \
opencv/samples/hal/c_hal \
opencv/samples/gpu \
opencv/samples/gpu/performance \
opencv/samples/directx \
opencv/samples/cpp \
opencv/samples/cpp/tutorial_code/xfeatures2D \
opencv/samples/cpp/tutorial_code/viz \
opencv/samples/cpp/tutorial_code/video \
opencv/samples/cpp/tutorial_code/photo/seamless_cloning \
opencv/samples/cpp/tutorial_code/photo/non_photorealistic_rendering \
opencv/samples/cpp/tutorial_code/photo/hdr_imaging \
opencv/samples/cpp/tutorial_code/photo/decolorization \
opencv/samples/cpp/tutorial_code/objectDetection \
opencv/samples/cpp/tutorial_code/ml/non_linear_svms \
opencv/samples/cpp/tutorial_code/ml/introduction_to_svm \
opencv/samples/cpp/tutorial_code/ml/introduction_to_pca \
opencv/samples/cpp/tutorial_code/introduction/windows_visual_studio_Opencv \
opencv/samples/cpp/tutorial_code/introduction/display_image \
opencv/samples/cpp/tutorial_code/gpu/gpu-basics-similarity \
opencv/samples/cpp/tutorial_code/features2D/AKAZE_tracking \
opencv/samples/cpp/tutorial_code/features2D \
opencv/samples/cpp/tutorial_code/core/mat_the_basic_image_container \
opencv/samples/cpp/tutorial_code/core/mat_mask_operations \
opencv/samples/cpp/tutorial_code/core/ippasync \
opencv/samples/cpp/tutorial_code/core/interoperability_with_OpenCV_1 \
opencv/samples/cpp/tutorial_code/core/how_to_scan_images \
opencv/samples/cpp/tutorial_code/core/file_input_output \
opencv/samples/cpp/tutorial_code/core/discrete_fourier_transform \
opencv/samples/cpp/tutorial_code/core/Matrix \
opencv/samples/cpp/tutorial_code/calib3d/stereoBM \
opencv/samples/cpp/tutorial_code/calib3d/real_time_pose_estimation/src \
opencv/samples/cpp/tutorial_code/calib3d/camera_calibration \
opencv/samples/cpp/tutorial_code/TrackingMotion \
opencv/samples/cpp/tutorial_code/ShapeDescriptors \
opencv/samples/cpp/tutorial_code/ImgTrans \
opencv/samples/cpp/tutorial_code/ImgProc \
opencv/samples/cpp/tutorial_code/Histograms_Matching \
opencv/samples/cpp/tutorial_code/HighGUI/video-write \
opencv/samples/cpp/tutorial_code/HighGUI/video-input-psnr-ssim \
opencv/samples/cpp/tutorial_code/HighGUI/GDAL_IO \
opencv/samples/cpp/tutorial_code/HighGUI \
opencv/samples/cpp/example_cmake \
opencv/samples/android/tutorial-4-opencl/jni \
opencv/samples/android/tutorial-2-mixedprocessing/jni \
opencv/samples/android/hello-android \
opencv/samples/android/face-detection/jni \
opencv/release/modules/videostab \
opencv/release/modules/videostab/CMakeFiles/opencv_videostab_pch_dephelp.dir \
opencv/release/modules/videostab/CMakeFiles/opencv_videostab.dir/src \
opencv/release/modules/videoio \
opencv/release/modules/videoio/CMakeFiles/opencv_videoio_pch_dephelp.dir \
opencv/release/modules/videoio/CMakeFiles/opencv_videoio.dir/src \
opencv/release/modules/videoio/CMakeFiles/opencv_test_videoio_pch_dephelp.dir \
opencv/release/modules/videoio/CMakeFiles/opencv_test_videoio.dir/test \
opencv/release/modules/videoio/CMakeFiles/opencv_perf_videoio_pch_dephelp.dir \
opencv/release/modules/videoio/CMakeFiles/opencv_perf_videoio.dir/perf \
opencv/release/modules/video \
opencv/release/modules/video/CMakeFiles/opencv_video_pch_dephelp.dir \
opencv/release/modules/video/CMakeFiles/opencv_video.dir/src \
opencv/release/modules/video/CMakeFiles/opencv_video.dir \
opencv/release/modules/video/CMakeFiles/opencv_test_video_pch_dephelp.dir \
opencv/release/modules/video/CMakeFiles/opencv_test_video.dir/test \
opencv/release/modules/video/CMakeFiles/opencv_test_video.dir/test/ocl \
opencv/release/modules/video/CMakeFiles/opencv_perf_video_pch_dephelp.dir \
opencv/release/modules/video/CMakeFiles/opencv_perf_video.dir/perf \
opencv/release/modules/video/CMakeFiles/opencv_perf_video.dir/perf/opencl \
opencv/release/modules/ts \
opencv/release/modules/ts/CMakeFiles/opencv_ts_pch_dephelp.dir \
opencv/release/modules/ts/CMakeFiles/opencv_ts.dir/src \
opencv/release/modules/superres \
opencv/release/modules/superres/CMakeFiles/opencv_test_superres_pch_dephelp.dir \
opencv/release/modules/superres/CMakeFiles/opencv_test_superres.dir/test \
opencv/release/modules/superres/CMakeFiles/opencv_superres_pch_dephelp.dir \
opencv/release/modules/superres/CMakeFiles/opencv_superres.dir/src \
opencv/release/modules/superres/CMakeFiles/opencv_superres.dir \
opencv/release/modules/superres/CMakeFiles/opencv_perf_superres_pch_dephelp.dir \
opencv/release/modules/superres/CMakeFiles/opencv_perf_superres.dir/perf \
opencv/release/modules/stitching \
opencv/release/modules/stitching/CMakeFiles/opencv_test_stitching_pch_dephelp.dir \
opencv/release/modules/stitching/CMakeFiles/opencv_test_stitching.dir/test \
opencv/release/modules/stitching/CMakeFiles/opencv_test_stitching.dir/test/ocl \
opencv/release/modules/stitching/CMakeFiles/opencv_stitching_pch_dephelp.dir \
opencv/release/modules/stitching/CMakeFiles/opencv_stitching.dir/src \
opencv/release/modules/stitching/CMakeFiles/opencv_stitching.dir \
opencv/release/modules/stitching/CMakeFiles/opencv_perf_stitching_pch_dephelp.dir \
opencv/release/modules/stitching/CMakeFiles/opencv_perf_stitching.dir/perf \
opencv/release/modules/stitching/CMakeFiles/opencv_perf_stitching.dir/perf/opencl \
opencv/release/modules/shape \
opencv/release/modules/shape/CMakeFiles/opencv_test_shape_pch_dephelp.dir \
opencv/release/modules/shape/CMakeFiles/opencv_test_shape.dir/test \
opencv/release/modules/shape/CMakeFiles/opencv_shape_pch_dephelp.dir \
opencv/release/modules/shape/CMakeFiles/opencv_shape.dir/src \
opencv/release/modules/photo \
opencv/release/modules/photo/CMakeFiles/opencv_test_photo_pch_dephelp.dir \
opencv/release/modules/photo/CMakeFiles/opencv_test_photo.dir/test \
opencv/release/modules/photo/CMakeFiles/opencv_test_photo.dir/test/ocl \
opencv/release/modules/photo/CMakeFiles/opencv_photo_pch_dephelp.dir \
opencv/release/modules/photo/CMakeFiles/opencv_photo.dir/src \
opencv/release/modules/photo/CMakeFiles/opencv_photo.dir \
opencv/release/modules/photo/CMakeFiles/opencv_perf_photo_pch_dephelp.dir \
opencv/release/modules/photo/CMakeFiles/opencv_perf_photo.dir/perf \
opencv/release/modules/photo/CMakeFiles/opencv_perf_photo.dir/perf/opencl \
opencv/release/modules/objdetect \
opencv/release/modules/objdetect/CMakeFiles/opencv_test_objdetect_pch_dephelp.dir \
opencv/release/modules/objdetect/CMakeFiles/opencv_test_objdetect.dir/test \
opencv/release/modules/objdetect/CMakeFiles/opencv_test_objdetect.dir/test/opencl \
opencv/release/modules/objdetect/CMakeFiles/opencv_perf_objdetect_pch_dephelp.dir \
opencv/release/modules/objdetect/CMakeFiles/opencv_perf_objdetect.dir/perf \
opencv/release/modules/objdetect/CMakeFiles/opencv_perf_objdetect.dir/perf/opencl \
opencv/release/modules/objdetect/CMakeFiles/opencv_objdetect_pch_dephelp.dir \
opencv/release/modules/objdetect/CMakeFiles/opencv_objdetect.dir/src \
opencv/release/modules/objdetect/CMakeFiles/opencv_objdetect.dir \
opencv/release/modules/ml \
opencv/release/modules/ml/CMakeFiles/opencv_test_ml_pch_dephelp.dir \
opencv/release/modules/ml/CMakeFiles/opencv_test_ml.dir/test \
opencv/release/modules/ml/CMakeFiles/opencv_ml_pch_dephelp.dir \
opencv/release/modules/ml/CMakeFiles/opencv_ml.dir/src \
opencv/release/modules/java \
opencv/release/modules/java/CMakeFiles/opencv_java.dir \
opencv/release/modules/java/CMakeFiles/opencv_java.dir/generator/src/cpp \
opencv/release/modules/java/CMakeFiles/opencv_java.dir/__/features2d/misc/java/src/cpp \
opencv/release/modules/java/CMakeFiles/opencv_java.dir/__/core/misc/java/src/cpp \
opencv/release/modules/imgproc \
opencv/release/modules/imgproc/CMakeFiles/opencv_test_imgproc_pch_dephelp.dir \
opencv/release/modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test \
opencv/release/modules/imgproc/CMakeFiles/opencv_test_imgproc.dir/test/ocl \
opencv/release/modules/imgproc/CMakeFiles/opencv_perf_imgproc_pch_dephelp.dir \
opencv/release/modules/imgproc/CMakeFiles/opencv_perf_imgproc.dir/perf \
opencv/release/modules/imgproc/CMakeFiles/opencv_perf_imgproc.dir/perf/opencl \
opencv/release/modules/imgproc/CMakeFiles/opencv_imgproc_pch_dephelp.dir \
opencv/release/modules/imgproc/CMakeFiles/opencv_imgproc.dir/src \
opencv/release/modules/imgproc/CMakeFiles/opencv_imgproc.dir \
opencv/release/modules/imgcodecs \
opencv/release/modules/imgcodecs/CMakeFiles/opencv_test_imgcodecs_pch_dephelp.dir \
opencv/release/modules/imgcodecs/CMakeFiles/opencv_test_imgcodecs.dir/test \
opencv/release/modules/imgcodecs/CMakeFiles/opencv_perf_imgcodecs_pch_dephelp.dir \
opencv/release/modules/imgcodecs/CMakeFiles/opencv_perf_imgcodecs.dir/perf \
opencv/release/modules/imgcodecs/CMakeFiles/opencv_imgcodecs_pch_dephelp.dir \
opencv/release/modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src \
opencv/release/modules/highgui \
opencv/release/modules/highgui/CMakeFiles/opencv_test_highgui_pch_dephelp.dir \
opencv/release/modules/highgui/CMakeFiles/opencv_test_highgui.dir/test \
opencv/release/modules/highgui/CMakeFiles/opencv_highgui_pch_dephelp.dir \
opencv/release/modules/highgui/CMakeFiles/opencv_highgui.dir/src \
opencv/release/modules/flann \
opencv/release/modules/flann/CMakeFiles/opencv_test_flann_pch_dephelp.dir \
opencv/release/modules/flann/CMakeFiles/opencv_test_flann.dir/test \
opencv/release/modules/flann/CMakeFiles/opencv_flann_pch_dephelp.dir \
opencv/release/modules/flann/CMakeFiles/opencv_flann.dir/src \
opencv/release/modules/features2d \
opencv/release/modules/features2d/CMakeFiles/opencv_test_features2d_pch_dephelp.dir \
opencv/release/modules/features2d/CMakeFiles/opencv_test_features2d.dir/test \
opencv/release/modules/features2d/CMakeFiles/opencv_test_features2d.dir/test/ocl \
opencv/release/modules/features2d/CMakeFiles/opencv_perf_features2d_pch_dephelp.dir \
opencv/release/modules/features2d/CMakeFiles/opencv_perf_features2d.dir/perf \
opencv/release/modules/features2d/CMakeFiles/opencv_perf_features2d.dir/perf/opencl \
opencv/release/modules/features2d/CMakeFiles/opencv_features2d_pch_dephelp.dir \
opencv/release/modules/features2d/CMakeFiles/opencv_features2d.dir/src \
opencv/release/modules/features2d/CMakeFiles/opencv_features2d.dir/src/kaze \
opencv/release/modules/features2d/CMakeFiles/opencv_features2d.dir \
opencv/release/modules/core \
opencv/release/modules/core/CMakeFiles/opencv_test_core_pch_dephelp.dir \
opencv/release/modules/core/CMakeFiles/opencv_test_core.dir/test \
opencv/release/modules/core/CMakeFiles/opencv_test_core.dir/test/ocl \
opencv/release/modules/core/CMakeFiles/opencv_perf_core_pch_dephelp.dir \
opencv/release/modules/core/CMakeFiles/opencv_perf_core.dir/perf \
opencv/release/modules/core/CMakeFiles/opencv_perf_core.dir/perf/opencl \
opencv/release/modules/core/CMakeFiles/opencv_perf_core.dir/perf/cuda \
opencv/release/modules/core/CMakeFiles/opencv_core_pch_dephelp.dir \
opencv/release/modules/core/CMakeFiles/opencv_core.dir/src \
opencv/release/modules/core/CMakeFiles/opencv_core.dir/src/opencl/runtime \
opencv/release/modules/core/CMakeFiles/opencv_core.dir \
opencv/release/modules/calib3d \
opencv/release/modules/calib3d/CMakeFiles/opencv_test_calib3d_pch_dephelp.dir \
opencv/release/modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/test \
opencv/release/modules/calib3d/CMakeFiles/opencv_test_calib3d.dir/test/opencl \
opencv/release/modules/calib3d/CMakeFiles/opencv_perf_calib3d_pch_dephelp.dir \
opencv/release/modules/calib3d/CMakeFiles/opencv_perf_calib3d.dir/perf \
opencv/release/modules/calib3d/CMakeFiles/opencv_perf_calib3d.dir/perf/opencl \
opencv/release/modules/calib3d/CMakeFiles/opencv_calib3d_pch_dephelp.dir \
opencv/release/modules/calib3d/CMakeFiles/opencv_calib3d.dir/src \
opencv/release/modules/calib3d/CMakeFiles/opencv_calib3d.dir \
opencv/release/apps/traincascade/CMakeFiles/opencv_traincascade.dir \
opencv/release/apps/createsamples/CMakeFiles/opencv_createsamples.dir \
opencv/release/apps/annotation/CMakeFiles/opencv_annotation.dir \
opencv/release/CMakeFiles/CheckTypeSize \
opencv/release/CMakeFiles/2.8.12.2/CompilerIdCXX \
opencv/release/CMakeFiles/2.8.12.2/CompilerIdC \
opencv/release/3rdparty/openexr/CMakeFiles/IlmImf.dir/Imath \
opencv/release/3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmThread \
opencv/release/3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf \
opencv/release/3rdparty/openexr/CMakeFiles/IlmImf.dir/Iex \
opencv/release/3rdparty/openexr/CMakeFiles/IlmImf.dir/Half \
opencv/release/3rdparty/libwebp/CMakeFiles/libwebp.dir/utils \
opencv/release/3rdparty/libwebp/CMakeFiles/libwebp.dir/mux \
opencv/release/3rdparty/libwebp/CMakeFiles/libwebp.dir/enc \
opencv/release/3rdparty/libwebp/CMakeFiles/libwebp.dir/dsp \
opencv/release/3rdparty/libwebp/CMakeFiles/libwebp.dir/dec \
opencv/release/3rdparty/libtiff/CMakeFiles/libtiff.dir \
opencv/release/3rdparty/libjpeg/CMakeFiles/libjpeg.dir \
opencv/release/3rdparty/libjasper/CMakeFiles/libjasper.dir \
opencv/modules/world/src \
opencv/modules/viz/test \
opencv/modules/viz/src \
opencv/modules/viz/src/vtk \
opencv/modules/videostab/src \
opencv/modules/videoio/test \
opencv/modules/videoio/src \
opencv/modules/videoio/src/cap_winrt \
opencv/modules/videoio/perf \
opencv/modules/video/test \
opencv/modules/video/test/ocl \
opencv/modules/video/src \
opencv/modules/video/perf \
opencv/modules/video/perf/opencl \
opencv/modules/ts/src \
opencv/modules/superres/test \
opencv/modules/superres/src \
opencv/modules/superres/perf \
opencv/modules/stitching/test \
opencv/modules/stitching/test/ocl \
opencv/modules/stitching/src \
opencv/modules/stitching/perf \
opencv/modules/stitching/perf/opencl \
opencv/modules/shape/test \
opencv/modules/shape/src \
opencv/modules/python/src2 \
opencv/modules/photo/test \
opencv/modules/photo/test/ocl \
opencv/modules/photo/src \
opencv/modules/photo/perf \
opencv/modules/photo/perf/opencl \
opencv/modules/objdetect/test \
opencv/modules/objdetect/test/opencl \
opencv/modules/objdetect/src \
opencv/modules/objdetect/perf \
opencv/modules/objdetect/perf/opencl \
opencv/modules/ml/test \
opencv/modules/ml/src \
opencv/modules/java/generator/src/cpp \
opencv/modules/imgproc/test \
opencv/modules/imgproc/test/ocl \
opencv/modules/imgproc/src \
opencv/modules/imgproc/perf \
opencv/modules/imgproc/perf/opencl \
opencv/modules/imgcodecs/test \
opencv/modules/imgcodecs/src \
opencv/modules/imgcodecs/perf \
opencv/modules/highgui/test \
opencv/modules/highgui/src \
opencv/modules/flann/test \
opencv/modules/flann/src \
opencv/modules/features2d/test \
opencv/modules/features2d/test/ocl \
opencv/modules/features2d/src \
opencv/modules/features2d/src/kaze \
opencv/modules/features2d/perf \
opencv/modules/features2d/perf/opencl \
opencv/modules/features2d/misc/java/src/cpp \
opencv/modules/cudev/test \
opencv/modules/cudev/src \
opencv/modules/cudawarping/test \
opencv/modules/cudawarping/src \
opencv/modules/cudawarping/perf \
opencv/modules/cudastereo/test \
opencv/modules/cudastereo/src \
opencv/modules/cudastereo/perf \
opencv/modules/cudaoptflow/test \
opencv/modules/cudaoptflow/src \
opencv/modules/cudaoptflow/perf \
opencv/modules/cudaobjdetect/test \
opencv/modules/cudaobjdetect/src \
opencv/modules/cudaobjdetect/perf \
opencv/modules/cudalegacy/test \
opencv/modules/cudalegacy/src \
opencv/modules/cudalegacy/perf \
opencv/modules/cudaimgproc/test \
opencv/modules/cudaimgproc/src \
opencv/modules/cudaimgproc/perf \
opencv/modules/cudafilters/test \
opencv/modules/cudafilters/src \
opencv/modules/cudafilters/perf \
opencv/modules/cudafeatures2d/test \
opencv/modules/cudafeatures2d/src \
opencv/modules/cudafeatures2d/perf \
opencv/modules/cudacodec/test \
opencv/modules/cudacodec/src \
opencv/modules/cudacodec/perf \
opencv/modules/cudabgsegm/test \
opencv/modules/cudabgsegm/src \
opencv/modules/cudabgsegm/perf \
opencv/modules/cudaarithm/test \
opencv/modules/cudaarithm/src \
opencv/modules/cudaarithm/perf \
opencv/modules/core/test \
opencv/modules/core/test/ocl \
opencv/modules/core/src \
opencv/modules/core/src/opencl/runtime \
opencv/modules/core/perf \
opencv/modules/core/perf/opencl \
opencv/modules/core/perf/cuda \
opencv/modules/core/misc/java/src/cpp \
opencv/modules/calib3d/test \
opencv/modules/calib3d/test/opencl \
opencv/modules/calib3d/src \
opencv/modules/calib3d/perf \
opencv/modules/calib3d/perf/opencl \
opencv/cmake/checks \
opencv/apps/traincascade \
opencv/apps/createsamples \
opencv/apps/annotation \
opencv/3rdparty/zlib \
opencv/3rdparty/tbb \
opencv/3rdparty/openexr/Imath \
opencv/3rdparty/openexr/IlmThread \
opencv/3rdparty/openexr/IlmImf \
opencv/3rdparty/openexr/Iex \
opencv/3rdparty/openexr/Half \
opencv/3rdparty/libwebp/utils \
opencv/3rdparty/libwebp/mux \
opencv/3rdparty/libwebp/enc \
opencv/3rdparty/libwebp/dsp \
opencv/3rdparty/libwebp/demux \
opencv/3rdparty/libwebp/dec \
opencv/3rdparty/libwebp/cpu-features \
opencv/3rdparty/libtiff \
opencv/3rdparty/libpng \
opencv/3rdparty/libpng/arm \
opencv/3rdparty/libjpeg \
opencv/3rdparty/libjasper \
Source\ Files \
Header\ Files \

